#!/usr/bin/python
import subprocess
import sys

from utils import write_config, read_config

if not write_config():
    sys.exit(0)

# Open up changed ports
config = read_config()
port = config.get('admin', {}).get('port')
subprocess.check_output(['open-port', str(port)])
